Zajecia1
t0meck-pj/sop2023-24_21c pull request #1
Opened 2024-03-18 16:08 UTC by HexonBoi

Rozwiazanie, mam nadzieje ze poprawnie

2024-03-18 22:18 UTC, t0meck-pj requested changes
proszę poprawić PR.
Dodatkowo proszę w rozwiązaniu zadania trzymać się wymagań dotyczących formatowania. 80 znaków w wierszu.

2024-03-18 22:18 UTC, t0meck-pj commented on t0meck-pj-TomaszIdzikowski/pamietnik.txt
Nie edytujemy plików innych użytkowników.

2024-03-18 22:18 UTC, t0meck-pj commented on s27136-NikodemTunowski/pamietnik.txt
Pamiętnik do głównego brancha. Tu ma być tylko i wyłącznie plik z instalacją debiana. Nic więcej.

2024-03-18 22:18 UTC, t0meck-pj commented on README.md
Czemu edytowałeś ten plik?

2024-03-19 15:27 UTC, HexonBoi commented on README.md
Nic w nim nie zmienialem, musial mi sie wgrac sam

2024-03-19 18:36 UTC, HexonBoi commented
Poprawione, czy do mastera też mam zrobić PR?

2024-03-19 23:26 UTC, t0meck-pj commented on README.md
To nie jest odpowiedź inżynierska. Nawet jeśli jest jakiś automat wykonujący jakieś zadanie, Twoim zadaniem jest zrozumienie tego jak działa i dlaczego stało się to co się stało. Także należy dociekać tego co się stało. Komputer jest urządzeniem niesłychanie prostym. Jeśli nie dostanie instrukcji to nic nie zrobi.

2024-03-19 23:28 UTC, t0meck-pj commented
Do mastera PR z samym pamiętnikiem.
Tekst jest napisany błędnie i za krótki nawet bym go sprawdzał na tym etapie. To ma być kompendium/biblia z opisem absolutnie wszystkiego co się opisać da.
Ponadto do łamania wyrazów używa się tzw. pauz czyli minusów/myślników.
Jednakże prosiłbym by łamać wiersze przy całych wyrazach gdyż łatwiej się to wtedy czyta.

2024-04-03 17:26 UTC, HexonBoi commented on README.md
Wrzucałem pliki poprzez strone co spowodowało ich nadpisanie mimo braku różnicy miedzy plikami

2024-04-16 21:30 UTC, t0meck-pj approved these changes
Zatwierdzam warunkowo w by zostało to poprawione inkrementacyjnie w kolejnych PR.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +połączenie sieciowe).
Ej ale takie rzeczy jak łamanie wierszy to robimy rzetelnie a nie łamiemy tam gdzie jest dłuższa linia i zostawiamy jedno słowo w wierszu.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +i
kolejny raz

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +wirtualizacji. Inne typy można użyć jeśli zgrywamy wirtualke z inne środowiska
Opisz wszystkie formaty dysków

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> + tekstowym, to samo z przeciągnij i upuść, ponieważ to system tekstowy.
System nie jest tekstowy tylko operacyjny.
Tekstowy to jest interfejs.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +maszynie a szyfrowanie spowalnia prace maszyny i szybkosc przegladania
Kiedy może być potrzeba włączenia tej opcji?

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +typu nośników (nikt już chyba nie używa).
To dyskietka wirtualna. Nie fizyczna. Więc na komputerze będziesz miał jedynie plik z zawartością dyskietki. Podobnie jak w przypadku pliku iso płyty instalacyjnej.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +Od tego momentu zmienilem jezyk Oracle na angielski aby ułatwić sobie research
Mianem Oracle w dziedzinie IT nazywa się przeważnie bazę danych firmy Oracle z której firma ta słynie.
Sugerowałbym odnosić się do VirtualBoxa wprost czyli VirtualBox.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +w Zakladce display w screen nic nie zmieniam, pamiec video 16mb wystarczy,
Skąd wiesz, że 16mb wystarczy? W jaki sposób to zostało wyliczone?

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +serwera VRDP.
klienta

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +typ adaptera zostawiam domyslny, inne typy oferuja miedzy innymi inny limit
opisz wszystkie dostępne typy oraz kiedy należy który stosować
I proszę opisz to w postaci listy nienumerowanej. Gdy wszystko jest w jednym bloku tekstu słabowidoczne jest ile tak naprawdę jest tam opcji.
Czyli zamiast tekstu w postaci:
> aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbccccccccccccccccccdddddddddddddddddeeeeeeeeeeeeeeeffffffffffffffffffgggggggggggggggggggghhhhhhhhhhhhhhhhhiiiiiiiiiiiiiiiiiijjjjjjjjjjjjjjjjjkkkkkkkkkkkkkklllllllllllllllllllllmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnooooooooooooooooooooopppppppppppppppppppppqqqqqqqqqqqqqqqqqqqqrrrrrrrrrrrrrrrrrrrrrrrrrssssssssssssssssssstttttttttttttttttttttttttttuuuuuuuuuuuuuuuuuuuuuuuuvvvvvvvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzz

Zrobić coś w tym stylu:
> - aaaaaaaaaaaaaaaaaaa
> - bbbbbbbbbbbbbbbb
> - cccccccccccccccccccc
> - dddddddddddddddd
> ...

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +W Serial portach zostawiam wszystko wyłączone, porty seryjne przydaja sie
seryjne -> szeregowe

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +dzisiaj tylko do debugowania kernela, wiec w przypadku takiej potrzeby nalezy
A gdy masz jakiś stary soft używany do flashowania firmware-u do starych urządzeń i na nowym komputerze tego normalnie nie uruchomisz ale masz do tego VM-kę na VB. Wtedy aktywujesz te porty i przez adapter podpinasz się komputerem do urządzenia ale cała akcja sterowana jest z wnętrza wirtualki. Więc to wcale nie jest tylko i wyłącznie do debuggowania kernela.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +Odpalamy wirtualke
Proszę o wprowadzenie jakiejś struktury tekstu i poprawne formatowanie. Zlewa się to wszystko ze sobą.
Tu zaczynasz proces instalacji ale można by było to rozdzielić jakąś dłuższą przerwą lub nawet jakimś tekstowym nagłówkiem dobrze widocznym bez skupiania się na merytoryce tekstu.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +Wybieram język Angielski, dla prostoty researchowania problemów które napotkam
Już wybierasz język? A gdzie opis wszystkich opcji w menu bootującym wraz z przykładem ich zastosowania?

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +domena - amogus
Do czego jest domena? Kiedy należy podać tu jakąkolwiek wartość?

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +4GB - Swap - Logical (zapasowa pamięć dla systemu gdyby RAM się przepełniał)
Na jakiej postawie przydzielasz tyle pamięci na przestrzeń wymiany?

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +ext4 journaling file system - Ext2 ale z journalingiem danych, lepiej
Tu masz błąd.
ext2+journaling = ext3

ext4 to system plików napisany od początku i niekompatybilny z poprzednimi generacjami systemu plików ext.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +uszkodzenia lub przypadkowego nadpisania.
Nie. To nie historia plików tylko historia wykonywanych operacji na dysku. Ma ona zabezpieczyć przed utratą danych w wypadku utraty zasilania i praktycznie tylko wtedy. Nie są tam przechowywane dane plików z poprzednich wersji.

Jest tam tylko informacja w stylu:
- journal: zaczynam zapis na dysk
- dane: teraz realizowany jest faktyczny zapis danych na dysku
- journal: zakończono operacje zapisu na dysku

Z powyższego można odzyskać jedynie ostatnią operację. Nie ma tam danych tylko rekord tego ŻE był zapis i ewentualnie można go po restarcie próbować ponowić jeśli jest to dostępne dla narzędzia zlecającego wykonanie zapisu na dysk.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +miejscu, dopiero po ostatnim zapisie oryginalny plik jest podmieniony.
Tu mówisz o opcji montowania tzw. copy-on-write. Ale btrfs wcale nie musi jej używać.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +FAT32 File System - Nowsza i lepsza wersja FAT16, limit partycji to 16GB a
Partycje ponad 16gb są możliwe na systemie plików FAT32 tylko wtedy rozmiar sektora jest większy.

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +physical volume for LVM - takie partycje nie zmieniaja etykiety po restartach
???

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +noseuid - wyłączenie interpretowania bitów SUID i SGID, odpowiadaja one za
Tu jest błąd

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +noexec - zabrania wykonywania jakichkolwiek plików wykonywalnych/bibliotek na
biblioteki nie są wykonywalne wprost

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +user_xattr - Rzoszerzone atrybuty użytkownika, czyli dodatkowe metadane które
Rzoszerzone

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +odmawiam w ankiecie najpopularniejszych pakietow ze wzgledu na to ze to
Do czego są używane dane zebrane z tej ankiety?

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +Debian desktop enviroment - metapakiet zawierajacy wszystkie niezbedne pakiety
należy zrobić porównanie środowisk graficznych względem:
- wymagań sprzętowych
- wydajności
- ergonomii
- bezpieczeństwa

2024-04-16 21:30 UTC, t0meck-pj commented on s27136-NikodemTunowski/zajecia1/instalacja_debian_linux.txt
> +instaluje grub-pc ze wzgledu ze debian to jedyny system na tej wirtualce, bez
No i znowu. Zlewa się to z instalacją pakietów.
Chociaż jedna interlinia przerwy.

A merytorycznie:
Gdzie można zainstalować bootloader na dysku twardym?
Kiedy należy instalować w którym miejscu?

2024-04-16 21:31 UTC, merged